image: python:3.13.1-bookworm

stages:
  - run
  - docs

before_script:
  - apt-get update -y
  - apt-get install -y doxygen
  - make install

run:
  stage: run
  script:
    - make run
  artifacts:
    paths:
      - images/*

docs:
  stage: docs
  script:
    - make doc
  artifacts:
    paths:
      - docs/html/