image: python:3.10-bookworm

stages:
  - run
  - docs

run:
  stage: run
  script:
    - make install run
  artifacts:
    paths:
      - images/*

docs:
  stage: docs
  script:
    - apt-get update -y
    - apt-get install -y doxygen
    - make doc
  artifacts:
    paths:
      - docs/html/